### ISSUE TITLE
List items don't display properly in the post preview

### ISSUE THREAD

**Issue by lunasorcery** [ChaiaEran/RuSShdown#5]
<img width="1677" alt="Screenshot 2024-09-11 at 22 27 01" src="https://github.com/user-attachments/assets/81b29a65-eaec-4d22-a2f0-610e8b5c2384">

Looks like the culprit is the `.tabs li` in the CSS which is affecting the deeper child elements on the page in addition to the top-level elements it's been written for.
From a very quick glance, changing it to `.tabs > li` *should* fix the problem without introducing other issues?

**Comment by ChaiaEran** [comment]
Ack, got it! Bug squashed, and hopefully the rest of the CSS shouldn't be affecting anything but the top-level elements.

Thanks!
